#!/bin/bash

source ../env.sh

# Define script mode execution
if [ $# -ge 1 ]; then script_mode=$1; else script_mode=MANUAL; fi

error()
{
  echo "dbg_auth script failed"
  if [ "$script_mode" != "AUTO" ]; then $SHELL; fi
  return 1
}

current_log_file=$projectdir/"DA/discovery.log"
echo "Generated by sh"> $current_log_file

"$stm32programmercli" "-c port=SWD debugauth=2" |tee -a $current_log_file
if [ $? -ne 0 ]; then error; return 1; fi

echo "discovery script success"
if [ "$script_mode" != "AUTO" ]; then $SHELL; fi

return
